apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pyrra-k8s-prom-access
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pyrra-kubernetes
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-monitoring
- kind: ServiceAccount
  name: pyrra-k8s
  namespace: openshift-monitoring
- kind: User
  name: vrutkovs
  namespace: openshift-monitoring
