apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: pyrra
    app.kubernetes.io/component: pyrra
    app.kubernetes.io/instance: pyrra
    app.kubernetes.io/part-of: pyrra-app
  name: pyrra
  namespace: openshift-monitoring
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: ghcr.io/vrutkovs/pyrra:devel
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local
