apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: openshift-apiserver-read-resource-response-errors
  namespace: pyrra
spec:
  description: ""
  indicator:
    ratio:
      errors:
        metric: apiserver_request_total{apiserver="openshift-apiserver",scope="resource",verb=~"LIST|GET",code=~"5.."}
      total:
        metric: apiserver_request_total{apiserver="openshift-apiserver",scope="resource",verb=~"LIST|GET"}
  target: "99.99"
  window: 4h
---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: openshift-apiserver-write-resource-response-errors
  namespace: pyrra
spec:
  description: ""
  indicator:
    ratio:
      errors:
        metric: apiserver_request_total{apiserver="openshift-apiserver",scope="resource",verb=~"POST|PUT|PATCH|DELETE",code=~"5.."}
      total:
        metric: apiserver_request_total{apiserver="openshift-apiserver",scope="resource",verb=~"POST|PUT|PATCH|DELETE"}
  target: "99"
  window: 4h
---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: openshift-apiserver-read-resource-request-latency
  namespace: pyrra
spec:
  description: ""
  indicator:
    latency:
      success:
        metric: apiserver_request_duration_seconds_bucket{apiserver="openshift-apiserver",scope=~"resource|",verb=~"LIST|GET",le="1"}
      total:
        metric: apiserver_request_duration_seconds_count{apiserver="openshift-apiserver",scope=~"resource|",verb=~"LIST|GET"}
  target: "99"
  window: 4h
---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: openshift-apiserver-auth-request-latency
  namespace: pyrra
spec:
  description: ""
  indicator:
    latency:
      success:
        metric: authentication_duration_seconds_bucket{apiserver="openshift-apiserver", le="1.024"}
      total:
        metric: authentication_duration_seconds_count{apiserver="openshift-apiserver"}
  target: "99"
  window: 4h
