---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: oauth-auth-request-latency
  namespace: pyrra
spec:
  description: ""
  indicator:
    latency:
      success:
        metric: authentication_duration_seconds_bucket{job="openshift-authentication", le="1.024"}
      total:
        metric: authentication_duration_seconds_count{job="openshift-authentication"}
  target: "99"
  window: 1d
---
