---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: cco-reconcile-latency
  namespace: pyrra
spec:
  description: ""
  indicator:
    latency:
      success:
        metric: cco_controller_reconcile_seconds_bucket{le="1"}
      total:
        metric: cco_controller_reconcile_seconds_count{}
  target: "99"
  window: 1d
