---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: controller-runtime-reconcile-latency
  namespace: pyrra
spec:
  description: ""
  indicator:
    latency:
      success:
        metric: controller_runtime_reconcile_time_seconds_bucket{le="0.1"}
      total:
        metric: controller_runtime_reconcile_time_seconds_count{}
  target: "99"
  window: 1d
