---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: csi-operations-latency
  namespace: pyrra
spec:
  description: ""
  indicator:
    latency:
      success:
        metric: csi_operations_seconds_bucket{le="0.1"}
      total:
        metric: csi_operations_seconds_count{}
  target: "99"
  window: 1d
---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: csi-sidecar-operations-latency
  namespace: pyrra
spec:
  description: ""
  indicator:
    latency:
      success:
        metric: csi_sidecar_operations_seconds_bucket{le="0.1"}
      total:
        metric: csi_sidecar_operations_seconds_count{}
  target: "99"
  window: 1d
