---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: cni-receive-dropped-packets
  namespace: pyrra
spec:
  description: ""
  indicator:
    ratio:
      errors:
        metric: container_network_receive_packets_dropped_total
      total:
        metric: container_network_receive_packets_total
  target: "99"
  window: 1d
---
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: cni-transmit-dropped-packets
  namespace: pyrra
spec:
  description: ""
  indicator:
    ratio:
      errors:
        metric: container_network_transmit_packets_dropped_total
      total:
        metric: container_network_transmit_packets_total
  target: "99"
  window: 1d
