kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: pyrra
  labels:
    app: pyrra
    app.kubernetes.io/component: pyrra
    app.kubernetes.io/instance: pyrra
    app.kubernetes.io/part-of: pyrra-app
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'ghcr.io/vrutkovs/pyrra:k8s-namespaced'
      importPolicy: {}
      referencePolicy:
        type: Local
