kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pyrra-k8s-prom-access
subjects:
  - kind: ServiceAccount
    name: default
    namespace: pyrra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
